export default  [
{ id: 1, title: "Pflegedusche centre1", url: 'https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5', description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged", subtitle: 'Sub Title 1' },
{ id: 2, title: "Pflegedusche centre2", url: 'https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5', description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged", subtitle: 'Sub Title 1' },
{ id: 3, title: "Pflegedusche centre3", url: 'https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5', description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged", subtitle: 'Sub Title 1' },
{ id: 4, title: "Pflegedusche centre4", url: 'https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5', description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged", subtitle: 'Sub Title 1' },
{ id: 5, title: "Pflegedusche centre5", url: 'https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5', description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged", subtitle: 'Sub Title 1' },
{ id: 6, title: "Pflegedusche centre6", url: 'https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5', description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged", subtitle: 'Sub Title 1' },
{ id: 7, title: "Pflegedusche centre7", url: 'https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5', description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged", subtitle: 'Sub Title 1' },
];
